### ISSUE TITLE
P53_ChIPSeq_Anno.py does not plot pies

### ISSUE THREAD

**Issue by varsh1090** [zhoulab/p53-chip-seq-anno#1]
Hi Victor,
    I know it has been a while, I am trying to run the script in - 
/ufrc/zhou/share/projects/bioinformatics/p53/P53_ChIPSeq_Anno/scripts/P53_ChIPSeq_Anno.py
It does not give me an error but there are no plots generated in the results/P53-ChIPSeq-Anno_count/plots folder. Could you please check this asap? Thank you.

**Comment by victorlin** [comment]
I think the problem is knowing how to run this script properly.

The command to generate the plots is `./run_anno_count`. Here is a copy of the console output when I ran it for the `Dm` and `Mammals` folders.

	(ve_local) [vlin@login1 scripts]$ ./run_anno_count
	Input subdirectories of /ufrc/zhou/share/projects/bioinformatics/p53/P53_ChIPSeq_Anno/data/Annos
	Enter folder(s) to use, separated by ",": Dm,Mammals
	Dm: finding occurences of values under the "Annotation" column... 
	Getting counts... done. Saved at: "Dm-count.txt"
	Creating pie plots... done. Saved at: "/ufrc/zhou/share/projects/bioinformatics/p53/P53_ChIPSeq_Anno/results/P53-ChIPSeq-Anno_count/plots/Dm-count_plots"
	Mammals: finding occurences of values under the "Annotation" column... 
	Getting counts... done. Saved at: "Mammals-count.txt"
	Creating pie plots... No counts for McDade_p53Adr_2.
	No counts for McDade_p53Adr_1.
	No counts for McDade_p53Cis_2.
	No counts for McDade_p53Cis_1.
	No counts for McDade_p53U_1.
	No counts for McDade_p53U_2.
	done. Saved at: "/ufrc/zhou/share/projects/bioinformatics/p53/P53_ChIPSeq_Anno/results/P53-ChIPSeq-Anno_count/plots/Mammals-count_plots"

Sorry this was not clear and even I had to dig into it. More details on how the script works is in [`processes.md`](https://github.com/zhoulab/p53-chip-seq-anno/blob/b0e9b8/processes.md).

**Comment by varsh1090** [comment]
Thanks Victor. It seems like there are some permission issues accessing the folders - 
[v.sundaresan@login1 scripts]$ ./run_anno_count
Input subdirectories of /ufrc/zhou/share/projects/bioinformatics/p53/P53_ChIPSeq_Anno/data/Annos
Enter folder(s) to use, separated by ",": Dm
Dm: finding occurences of values under the "Annotation" column...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "P53_ChIPSeq_Anno.py", line 230, in do_anno_count
    with open(os.path.join(output_dir, folder + '-count.txt'), 'w') as f:
IOError: [Errno 13] Permission denied: '/ufrc/zhou/share/projects/bioinformatics/p53/P53_ChIPSeq_Anno/results/P53-ChIPSeq-Anno_count/Dm-count.txt'

**Comment by victorlin** [comment]
Just updated the permissions – let me know if it works!

**Comment by varsh1090** [comment]
I think it works now, thank you!

**Comment by varsh1090** [comment]
Hi Victor, in some of the images the legend border and %) is cut. Could we move the legend box towards the left to fit all the contents please? Thanks.

**Comment by victorlin** [comment]
@varsh1090 I fixed the script so that it extends more to the right to include the full legend. Do you still want to move it to the left side?

**Comment by varsh1090** [comment]
Thanks Victor, that works. Also looks like we need to use - "module load python" before using the script on HPC, just for the documentation.

**Comment by varsh1090** [comment]
@victorlin, Could we make the % of the Annotation types - intergenic, intron, etc as part of the pie chart itself or maybe right outside the respective pie? That way we can remove the legend box to make the figures smaller and only have 1 common legend for the colors and Annotation types without (%). Thanks!

**Comment by victorlin** [comment]
Sure I will work on that – also let me know if you would like to change the colors or order of Annotation types displayed.

**Comment by varsh1090** [comment]
@victorlin, the colors look fine to me. Could we generate the figures without the legends and % in (or near) each pie and the legend box as a separate file? The order for legend below is fine, except the "non-coding" can be moved to the bottom.
![image](https://user-images.githubusercontent.com/17714019/45431070-d7ee9980-b674-11e8-9102-738687f81c8a.png)

**Comment by victorlin** [comment]
Updated the script to include no labels for slices with a value of less than 5%. The legend image (`legend.png`) is in the same results folder as the figures (ex. `/ufrc/zhou/share/projects/bioinformatics/p53/P53_ChIPSeq_Anno/results/P53-ChIPSeq-Anno_count/plots/Dm-count_plots/legend.png`)
